import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/Header.tsx';
import Sidebar from '@/components/Sidebar.tsx';
import { headers } from 'next/headers';
import { cn } from '@/utils/cn';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type pagePath = '/' | '/login';

const pagesConfig = {
  '/': {
    isHeader: true,
    isSidebar: true,
    isFooter: true,
  },
  '/login': {
    isHeader: false,
    isSidebar: false,
    isFooter: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const requestHeaders = headers();
  const pathname = requestHeaders.get('x-current-path');

  const { isHeader, isSidebar, isFooter } = pagesConfig[pathname as pagePath];

  return (
    <html lang="ko" className="h-full">
      <body
        className={cn(
          `relative h-full bg-customGray-1000 ${isHeader && 'pt-[60px]'}`,
        )}
      >
        {isHeader && <Header />}
        {isSidebar && <Sidebar />}
        <section className={cn(`h-full ${isSidebar && 'pl-[78px]'}`)}>
          {children}
        </section>
      </body>
    </html>
  );
}
