import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/Header.tsx';
import Sidebar from '@/components/Sidebar.tsx';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className="h-full">
      <body className="relative h-full bg-customGray-1000 pt-[60px]">
        <Header />
        <Sidebar />
        <section className="h-full pl-[78px]">{children}</section>
      </body>
    </html>
  );
}
